// <auto-generated />
using System;
using FiveSTAR_tracking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FiveSTAR_tracking.Migrations
{
    [DbContext(typeof(ProjectTaskContext))]
    [Migration("20181101193708_ProjectFiveStar")]
    partial class ProjectFiveStar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FiveSTAR_tracking.Models.ProjectsFiveStar", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ActCost");

                    b.Property<DateTime>("ActEndDate");

                    b.Property<decimal>("ActHours");

                    b.Property<string>("Description");

                    b.Property<decimal>("EstCost");

                    b.Property<DateTime>("EstEndtDate");

                    b.Property<decimal>("EstHours");

                    b.Property<int>("IdUsers");

                    b.Property<string>("ProjectManager");

                    b.Property<string>("ProjectName");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.ToTable("ProjectFiveStar");
                });

            modelBuilder.Entity("FiveSTAR_tracking.Models.ProjectTask", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("HoursWorked");

                    b.Property<string>("TaskName");

                    b.Property<decimal>("Task_Act_Cost");

                    b.Property<decimal>("Task_Est_Cost");

                    b.Property<int>("idUsers");

                    b.Property<int>("idVendor");

                    b.HasKey("ID");

                    b.ToTable("ProjectTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
